name: CI + Trigger Jenkins CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0'   # Change to your .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-build

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/doordie:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/doordie:latest

    - name: Get Jenkins crumb
      env:
        JENKINS_URL: ${{ secrets.JENKINS_URL }}
        JENKINS_USER: ${{ secrets.JENKINS_USER }}
        JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
      run: |
            CRUMB=$(curl -u "$JENKINS_USER:$JENKINS_API_TOKEN" -s "$JENKINS_URL/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)")
            echo "CRUMB=$CRUMB" >> $GITHUB_ENV


    - name: Trigger Jenkins Job
      env:
        JENKINS_URL: ${{ secrets.JENKINS_URL }}
        JENKINS_USER: ${{ secrets.JENKINS_USER }}
        JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
        JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
        CRUMB: ${{ env.CRUMB }}
      run: |
           curl -u "$JENKINS_USER:$JENKINS_API_TOKEN" -X POST "$JENKINS_URL/job/deploy-dotnet-api/build?token=$JENKINS_TOKEN" -H "$CRUMB"

